/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppRevenueRouteImport } from './routes/_app/revenue'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppInventoryRouteImport } from './routes/_app/inventory'
import { Route as AppEngineersRouteImport } from './routes/_app/engineers'
import { Route as AppCustomersRouteImport } from './routes/_app/customers'
import { Route as AppCallsRouteImport } from './routes/_app/calls'
import { Route as AppAllocationRouteImport } from './routes/_app/allocation'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRevenueRoute = AppRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppEngineersRoute = AppEngineersRouteImport.update({
  id: '/engineers',
  path: '/engineers',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppCallsRoute = AppCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => AppRoute,
} as any)
const AppAllocationRoute = AppAllocationRouteImport.update({
  id: '/allocation',
  path: '/allocation',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRoute
  '/allocation': typeof AppAllocationRoute
  '/calls': typeof AppCallsRoute
  '/customers': typeof AppCustomersRoute
  '/engineers': typeof AppEngineersRoute
  '/inventory': typeof AppInventoryRoute
  '/reports': typeof AppReportsRoute
  '/revenue': typeof AppRevenueRoute
  '/settings': typeof AppSettingsRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/allocation': typeof AppAllocationRoute
  '/calls': typeof AppCallsRoute
  '/customers': typeof AppCustomersRoute
  '/engineers': typeof AppEngineersRoute
  '/inventory': typeof AppInventoryRoute
  '/reports': typeof AppReportsRoute
  '/revenue': typeof AppRevenueRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/allocation': typeof AppAllocationRoute
  '/_app/calls': typeof AppCallsRoute
  '/_app/customers': typeof AppCustomersRoute
  '/_app/engineers': typeof AppEngineersRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/revenue': typeof AppRevenueRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/allocation'
    | '/calls'
    | '/customers'
    | '/engineers'
    | '/inventory'
    | '/reports'
    | '/revenue'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/allocation'
    | '/calls'
    | '/customers'
    | '/engineers'
    | '/inventory'
    | '/reports'
    | '/revenue'
    | '/settings'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/_app/allocation'
    | '/_app/calls'
    | '/_app/customers'
    | '/_app/engineers'
    | '/_app/inventory'
    | '/_app/reports'
    | '/_app/revenue'
    | '/_app/settings'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/revenue': {
      id: '/_app/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof AppRevenueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/engineers': {
      id: '/_app/engineers'
      path: '/engineers'
      fullPath: '/engineers'
      preLoaderRoute: typeof AppEngineersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calls': {
      id: '/_app/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof AppCallsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/allocation': {
      id: '/_app/allocation'
      path: '/allocation'
      fullPath: '/allocation'
      preLoaderRoute: typeof AppAllocationRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAllocationRoute: typeof AppAllocationRoute
  AppCallsRoute: typeof AppCallsRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppEngineersRoute: typeof AppEngineersRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRevenueRoute: typeof AppRevenueRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAllocationRoute: AppAllocationRoute,
  AppCallsRoute: AppCallsRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppEngineersRoute: AppEngineersRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppReportsRoute: AppReportsRoute,
  AppRevenueRoute: AppRevenueRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
